# Basic
title: Sakyaer
subtitle: 道可道
welcome_message: 
description: Unity开发者/UE4修炼中，探求创意之源。
creator: <a href="http://sakyaer.github.io">@onevcat</a>

url: "hhttp://sakyaer.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 归档, description: 博文归档, url: 'http://sakyaer.github.io'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: false
    # duoshuo:
# Social
social:
    weibo: sakyaer
    github: sakyaer
    twitter: sakyaer
    mail: sakyaer@foxmail.com

# Google Analytics
#ga:
#    id: UA-25719337-1
#    host: onevcat.com
